#!/bin/bash

if [[ -z "$AWS_REGION" ]] || [[ -z "$AWS_ENV" ]] ; then
    echo 'Requires $AWS_ENV and $AWS_REGION. Please set those and rerun.'
else
    docker build -t lambda-cloudwatch-slack .
    iam-docker-run \
       --image lambda-cloudwatch-slack \
       --profile $AWS_ENV \
       -e DEPLOY_BUCKET=${COMPANY:-company}-deploy-$AWS_ENV-$AWS_REGION \
       --full-entrypoint "npm run deploy"
fi
