service: sns-slack-lambda

# pin to a specific Serverless version
frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  region: ${env:AWS_REGION, 'us-east-1'}
  runtime: nodejs8.10
  deploymentBucket: ${opt:deployBucket}
  stage: ${env:AWS_ENV, 'dev'}
  logRetentionInDays: 14 # cloudwatch logs
  timeout: 10 # seconds
  versionFunctions: true

package:
      exclude:
        - .git/**
        - .dockerignore
        - Dockerfile
        - images

functions:
  sns-slack-lambda:
    name: 'sns-slack-lambda-${self:provider.stage}'
    handler: index.handler
    environment:
      UNENCRYPTED_HOOK_URL: ${ssm:/devops/sns-slack-lambda/HOOK_URL~true}
      KMS_ENCRYPTED_HOOK_URL: ${ssm:/devops/sns-slack-lambda/KMS_HOOK_URL~true}
      LOG_LEVEL: 'debug'
